# Generated by Django 5.0.6 on 2024-12-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word_tr',
            old_name='word_fr',
            new_name='word_pr',
        ),
        migrations.AlterField(
            model_name='word_tr',
            name='info',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='توضیحات به پارسی'),
        ),
        migrations.AlterField(
            model_name='word_tr',
            name='meaning',
            field=models.CharField(max_length=50, verbose_name='معنی در یک کلمه به پارسی'),
        ),
    ]
